export const FEEDBACK_POST_REQUEST = 'FEEDBACK_POST_REQUEST';
export const FEEDBACK_POST_SUCCESS = 'FEEDBACK_POST_SUCCESS';
export const FEEDBACK_POST_FAIL = 'FEEDBACK_POST_FAIL';

export const FEEDBACK_FETCH_REQUEST = 'FEEDBACK_FETCH_REQUEST';
export const FEEDBACK_FETCH_SUCCESS = 'FEEDBACK_FETCH_SUCCESS';
export const FEEDBACK_FETCH_FAIL = 'FEEDBACK_FETCH_FAIL';
