export const INSURANCE_POST_REQUEST = 'INSURANCE_POST_REQUEST';
export const INSURANCE_POST_SUCCESS = 'INSURANCE_POST_SUCCESS';
export const INSURANCE_POST_FAIL = 'INSURANCE_POST_FAIL';

export const INSURANCE_FETCH_REQUEST = 'INSURANCE_FETCH_REQUEST';
export const INSURANCE_FETCH_SUCCESS = 'INSURANCE_FETCH_SUCCESS';
export const INSURANCE_FETCH_FAIL = 'INSURANCE_FETCH_FAIL';

export const INSURANCE_REPORT_FETCH_REQUEST = 'INSURANCE_REPORT_FETCH_REQUEST';
export const INSURANCE_REPORT_FETCH_SUCCESS = 'INSURANCE_REPORT_FETCH_SUCCESS';
export const INSURANCE_REPORT_FETCH_FAIL = 'INSURANCE_REPORT_FETCH_FAIL';
export const INSURANCE_REPORT_FETCH_RESET = 'INSURANCE_REPORT_FETCH_RESET';
