export const INSURANCE_FETCH_REQUEST = 'INSURANCE_FETCH_REQUEST';
export const INSURANCE_FETCH_SUCCESS = 'INSURANCE_FETCH_SUCCESS';
export const INSURANCE_FETCH_FAIL = 'INSURANCE_FETCH_FAIL';
export const INSURANCE_FETCH_RESET = 'INSURANCE_FETCH_RESET';
