export const TAX_DETAILS_FETCH_REQUEST = 'TAX_DETAILS_FETCH_REQUEST';
export const TAX_DETAILS_FETCH_SUCCESS = 'TAX_DETAILS_FETCH_SUCCESS';
export const TAX_DETAILS_FETCH_FAIL = 'TAX_DETAILS_FETCH_FAIL';
