export const TAXPAYER_FETCH_REQUEST = 'TAXPAYER_FETCH_REQUEST';
export const TAXPAYER_FETCH_SUCCESS = 'TAXPAYER_FETCH_SUCCESS';
export const TAXPAYER_FETCH_FAIL = 'TAXPAYER_FETCH_FAIL';
export const TAXPAYER_FETCH_RESET = 'TAXPAYER_FETCH_RESET';
