export const TAXPAYER_FETCH_REQUEST = 'TAXPAYER_FETCH_REQUEST';
export const TAXPAYER_FETCH_SUCCESS = 'TAXPAYER_FETCH_SUCCESS';
export const TAXPAYER_FETCH_FAIL = 'TAXPAYER_FETCH_FAIL';
export const TAXPAYER_FETCH_RESET = 'TAXPAYER_FETCH_RESET';

export const TAXPAYER_SIGNUP_REQUEST = 'TAXPAYER_SIGNUP_REQUEST';
export const TAXPAYER_SIGNUP_SUCCESS = 'TAXPAYER_SIGNUP_SUCCESS';
export const TAXPAYER_SIGNUP_FAIL = 'TAXPAYER_SIGNUP_FAIL';
export const TAXPAYER_SIGNUP_RESET = 'TAXPAYER_SIGNUP_RESET';

export const TAXPAYER_LOGIN_REQUEST = 'TAXPAYER_LOGIN_REQUEST';
export const TAXPAYER_LOGIN_SUCCESS = 'TAXPAYER_LOGIN_SUCCESS';
export const TAXPAYER_LOGIN_FAIL = 'TAXPAYER_LOGIN_FAIL';
export const TAXPAYER_LOGIN_RESET = 'TAXPAYER_LOGIN_RESET';

export const TAXPAYER_DELETE_REQUEST = 'TAXPAYER_DELETE_REQUEST';
export const TAXPAYER_DELETE_SUCCESS = 'TAXPAYER_DELETE_SUCCESS';
export const TAXPAYER_DELETE_FAIL = 'TAXPAYER_DELETE_FAIL';
